const Menu = [
  // Breakfast Items
  {
    id: 1,
    image: "images/masaladosa.jpg",
    name: "Masala Dosa",
    category: "breakfast",
    price: "50₹",
    description: "Crispy dosa filled with spiced potato, served with chutneys and sambar.",
  },
  {
    id: 2,
    image: "images/idli.jpg",
    name: "Idli",
    category: "breakfast",
    price: "30₹",
    description: "Soft and fluffy steamed rice cakes, served with chutneys and sambar.",
  },
  {
    id: 3,
    image: "images/poha.jpg",
    name: "Poha",
    category: "breakfast",
    price: "20₹",
    description: "Flattened rice cooked with onions, potatoes, and spices, a light and healthy option.",
  },
  {
    id: 4,
    image: "images/upma.jpg",
    name: "Upma",
    category: "breakfast",
    price: "25₹",
    description: "Savory semolina dish cooked with vegetables and spices.",
  },

  // Lunch Items
  {
    id: 5,
    image: "images/chola.jpg",
    name: "Chola",
    category: "lunch",
    price: "50₹",
    description: "Spicy and flavorful chickpea curry, a hearty lunch option.",
  },
  {
    id: 6,
    image: "images/rajmarice.jpg",
    name: "Rajma Rice",
    category: "lunch",
    price: "60₹",
    description: "Classic comfort food, kidney beans cooked in a rich gravy served with rice.",
  },
  {
    id: 7,
    image: "images/paneertikka.jpg",
    name: "Paneer Tikka",
    category: "lunch",
    price: "150₹",
    description: "Grilled paneer cubes marinated with spices, a delicious and filling option.",
  },
  {
    id: 8,
    image: "images/butterchicken.jpg",
    name: "Butter Chicken",
    category: "lunch",
    price: "200₹",
    description: "Tender chicken cooked in a rich and creamy tomato-based sauce.",
  },
  {
    id: 9,
    image: "images/vegkorma.jpg",
    name: "Veg Korma",
    category: "lunch",
    price: "120₹",
    description: "Mixed vegetables cooked in a creamy and mildly spiced sauce.",
  },

  // Evening Snacks
  {
    id: 10,
    image: "images/allupakoida.jpg",
    name: "Allu Pakoida",
    category: "evening",
    price: "20₹",
    description: "Crispy and spicy potato fritters, perfect for evening tea.",
  },
  {
    id: 11,
    image: "images/samosa.jpg",
    name: "Samosa",
    category: "evening",
    price: "10₹",
    description: "Golden fried pastry filled with spiced potatoes and peas, a classic snack.",
  },
  {
    id: 12,
    image: "images/burger.jpg",
    name: "Burger",
    category: "evening",
    price: "70₹",
    description: "Juicy patty with fresh vegetables and sauces, a satisfying evening meal.",
  },
  {
    id: 13,
    image: "images/pizza.jpg",
    name: "Pizza",
    category: "evening",
    price: "80₹",
    description: "Cheesy and delicious pizza with your choice of toppings.",
  },
  {
    id: 14,
    image: "images/pavbhaji.jpg",
    name: "Pav Bhaji",
    category: "evening",
    price: "50₹",
    description: "Spicy mashed vegetables served with buttered bread rolls.",
  },
  {
    id: 15,
    image: "images/dhokla.jpg",
    name: "Dhokla",
    category: "evening",
    price: "40₹",
    description: "Steamed savory cake made from fermented rice and chickpea batter.",
  },
  {
    id: 16,
    image: "images/bhelpuri.jpg",
    name: "Bhel Puri",
    category: "evening",
    price: "30₹",
    description: "A tangy and spicy puffed rice snack mixed with vegetables and tamarind sauce.",
  },

  // Dinner Items
  {
    id: 17,
    image: "images/nonvegthali.jpg",
    name: "Non-Veg Thali",
    category: "dinner",
    price: "180₹",
    description: "A complete meal with a variety of non-vegetarian dishes, rice, and bread.",
  },
  {
    id: 18,
    image: "images/vegthali.jpg",
    name: "Veg Thali",
    category: "dinner",
    price: "120₹",
    description: "A wholesome meal with a variety of vegetarian dishes, rice, and bread.",
  },
  {
    id: 19,
    image: "images/chickenbiryani.jpg",
    name: "Chicken Biryani",
    category: "dinner",
    price: "200₹",
    description: "Aromatic basmati rice cooked with tender chicken pieces and spices.",
  },
  {
    id: 20,
    image: "images/fishcurry.jpg",
    name: "Fish Curry",
    category: "dinner",
    price: "220₹",
    description: "Fresh fish cooked in a tangy and spicy curry, served with rice.",
  },
  {
    id: 21,
    image: "images/dalmakhani.jpg",
    name: "Dal Makhani",
    category: "dinner",
    price: "150₹",
    description: "Creamy and rich lentil curry, a vegetarian favorite.",
  },
  {
    id: 22,
    image: "images/malakofta.jpg",
    name: "Malai Kofta",
    category: "dinner",
    price: "170₹",
    description: "Soft paneer and vegetable dumplings in a rich and creamy tomato gravy.",
  },

  // Dessert Items
  {
    id: 23,
    image: "images/sweet.jpg",
    name: "Sweets",
    category: "dessert",
    price: "60₹",
    description: "An assortment of traditional Indian sweets to end your meal on a sweet note.",
  },
  {
    id: 24,
    image: "images/icecream.jpg",
    name: "Ice Cream",
    category: "dessert",
    price: "60₹",
    description: "Chilled and creamy delight, available in various flavors.",
  },
  {
    id: 25,
    image: "images/gulabjamun.jpg",
    name: "Gulab Jamun",
    category: "dessert",
    price: "40₹",
    description: "Soft and spongy dumplings soaked in sugar syrup, a classic Indian dessert.",
  },
  {
    id: 26,
    image: "images/ricekheer.jpg",
    name: "Rice Kheer",
    category: "dessert",
    price: "50₹",
    description: "Creamy and aromatic rice pudding flavored with cardamom and saffron.",
  },
  {
    id: 27,
    image: "images/chocolatecake.jpg",
    name: "Chocolate Cake",
    category: "dessert",
    price: "80₹",
    description: "Rich and moist chocolate cake, a perfect end to your meal.",
  },
  {
    id: 28,
    image: "images/jalebi.jpg",
    name: "Jalebi",
    category: "dessert",
    price: "30₹",
    description: "Crispy and syrupy fried sweet, a traditional Indian treat.",
  },
];

export default Menu;
