const Menu = [
  // Breakfast Items
  {
    id: 1,
    image: "images/masaladosa.jpg",
    name: "Masala Dosa",
    category: "breakfast",
    price: "50₹",
    description: "Crispy dosa filled with spiced potato, served with chutneys and sambar.",
  },
  {
    id: 2,
    image: "images/idli.jpg",
    name: "Idli",
    category: "breakfast",
    price: "30₹",
    description: "Soft and fluffy steamed rice cakes, served with chutneys and sambar.",
  },
  {
    id: 3,
    image: "images/poha.jpg",
    name: "Poha",
    category: "breakfast",
    price: "20₹",
    description: "Flattened rice cooked with onions, potatoes, and spices, a light and healthy option.",
  },
  {
    id: 4,
    image: "images/upma.jpg",
    name: "Upma",
    category: "breakfast",
    price: "25₹",
    description: "Savory semolina dish cooked with vegetables and spices.",
  },
  {
    id: 5,
    image: "images/paratha.jpg",
    name: "Aloo Paratha",
    category: "breakfast",
    price: "40₹",
    description: "Stuffed whole wheat bread with spiced potato filling, served with yogurt and pickle.",
  },
  {
    id: 6,
    image: "images/pancakes.jpg",
    name: "Pancakes",
    category: "breakfast",
    price: "45₹",
    description: "Fluffy pancakes served with syrup, butter, and a side of fresh fruit.",
  },
  {
    id: 7,
    image: "images/eggsbacon.jpg",
    name: "Eggs & Bacon",
    category: "breakfast",
    price: "60₹",
    description: "Classic breakfast with scrambled eggs and crispy bacon, served with toast.",
  },
  {
    id: 8,
    image: "images/oats.jpg",
    name: "Oats Porridge",
    category: "breakfast",
    price: "35₹",
    description: "Nutritious oatmeal porridge with nuts, fruits, and honey.",
  },
  {
    id: 9,
    image: "images/englishbreakfast.jpg",
    name: "Full English Breakfast",
    category: "breakfast",
    price: "75₹",
    description: "A hearty breakfast with eggs, sausages, bacon, beans, and grilled tomatoes.",
  },
  {
    id: 10,
    image: "images/muffins.jpg",
    name: "Muffins",
    category: "breakfast",
    price: "30₹",
    description: "Freshly baked muffins with a variety of flavors including blueberry and chocolate chip.",
  },
  {
    id: 11,
    image: "images/crepes.jpg",
    name: "Crepes",
    category: "breakfast",
    price: "55₹",
    description: "Thin, delicate crepes filled with sweet or savory toppings.",
  },
  {
    id: 12,
    image: "images/cheesetoast.jpg",
    name: "Cheese Toast",
    category: "breakfast",
    price: "25₹",
    description: "Toasted bread with melted cheese, served with a side of salsa.",
  },
  {
    id: 13,
    image: "images/bagel.jpg",
    name: "Bagel with Cream Cheese",
    category: "breakfast",
    price: "40₹",
    description: "Freshly baked bagel served with a generous spread of cream cheese.",
  },
  {
    id: 14,
    image: "images/smoothiebowl.jpg",
    name: "Smoothie Bowl",
    category: "breakfast",
    price: "50₹",
    description: "Blended fruit smoothie topped with granola, nuts, and fresh fruit.",
  },
  {
    id: 15,
    image: "images/frenchtoast.jpg",
    name: "French Toast",
    category: "breakfast",
    price: "45₹",
    description: "Egg-soaked bread grilled to perfection, served with syrup and fruit.",
  },
  {
    id: 16,
    image: "images/fruitsalad.jpg",
    name: "Fruit Salad",
    category: "breakfast",
    price: "30₹",
    description: "A refreshing mix of seasonal fruits, perfect for a light start to the day.",
  },
  {
    id: 17,
    image: "images/eggbenedict.jpg",
    name: "Egg Benedict",
    category: "breakfast",
    price: "65₹",
    description: "Poached eggs on English muffins with hollandaise sauce.",
  },
  {
    id: 18,
    image: "images/cheerios.jpg",
    name: "Cheerios",
    category: "breakfast",
    price: "20₹",
    description: "Classic breakfast cereal served with milk.",
  },
  {
    id: 19,
    image: "images/fruityogurt.jpg",
    name: "Fruit Yogurt",
    category: "breakfast",
    price: "35₹",
    description: "Creamy yogurt topped with fresh fruit and a drizzle of honey.",
  },
  {
    id: 20,
    image: "images/avocadoToast.jpg",
    name: "Avocado Toast",
    category: "breakfast",
    price: "50₹",
    description: "Whole grain toast topped with creamy avocado and a sprinkle of salt and pepper.",
  },

  // Lunch Items
  {
    id: 21,
    image: "images/chola.jpg",
    name: "Chola",
    category: "lunch",
    price: "50₹",
    description: "Spicy and flavorful chickpea curry, a hearty lunch option.",
  },
  {
    id: 22,
    image: "images/rajmarice.jpg",
    name: "Rajma Rice",
    category: "lunch",
    price: "60₹",
    description: "Classic comfort food, kidney beans cooked in a rich gravy served with rice.",
  },
  {
    id: 23,
    image: "images/paneertikka.jpg",
    name: "Paneer Tikka",
    category: "lunch",
    price: "150₹",
    description: "Grilled paneer cubes marinated with spices, a delicious and filling option.",
  },
  {
    id: 24,
    image: "images/butterchicken.jpg",
    name: "Butter Chicken",
    category: "lunch",
    price: "200₹",
    description: "Tender chicken cooked in a rich and creamy tomato-based sauce.",
  },
  {
    id: 25,
    image: "images/vegkorma.jpg",
    name: "Veg Korma",
    category: "lunch",
    price: "120₹",
    description: "Mixed vegetables cooked in a creamy and mildly spiced sauce.",
  },
  {
    id: 26,
    image: "images/cholebhature.jpg",
    name: "Chole Bhature",
    category: "lunch",
    price: "70₹",
    description: "Deep-fried bread served with spicy chickpea curry.",
  },
  {
    id: 27,
    image: "images/vegpulao.jpg",
    name: "Veg Pulao",
    category: "lunch",
    price: "55₹",
    description: "Fragrant rice cooked with mixed vegetables and spices.",
  },
  {
    id: 28,
    image: "images/kadhicurry.jpg",
    name: "Kadhi Curry",
    category: "lunch",
    price: "60₹",
    description: "Yogurt-based curry with gram flour dumplings.",
  },
  {
    id: 29,
    image: "images/methiThepla.jpg",
    name: "Methi Thepla",
    category: "lunch",
    price: "50₹",
    description: "Spiced flatbreads made with fenugreek leaves, served with yogurt.",
  },
  {
    id: 30,
    image: "images/keemaPulao.jpg",
    name: "Keema Pulao",
    category: "lunch",
    price: "80₹",
    description: "Rice cooked with minced meat and aromatic spices.",
  },
  {
    id: 31,
    image: "images/vegetablesoup.jpg",
    name: "Vegetable Soup",
    category: "lunch",
    price: "40₹",
    description: "Hearty and nourishing soup made with fresh vegetables.",
  },
  {
    id: 32,
    image: "images/palakpaneer.jpg",
    name: "Palak Paneer",
    category: "lunch",
    price: "130₹",
    description: "Paneer cubes cooked in a rich spinach gravy.",
  },
  {
    id: 33,
    image: "images/pulao.jpg",
    name: "Pulao",
    category: "lunch",
    price: "60₹",
    description: "Aromatic rice dish cooked with mixed vegetables and spices.",
  },
  {
    id: 34,
    image: "images/prawnmasala.jpg",
    name: "Prawn Masala",
    category: "lunch",
    price: "220₹",
    description: "Prawns cooked in a spicy and flavorful masala.",
  },
  {
    id: 35,
    image: "images/vegetablebiryani.jpg",
    name: "Vegetable Biryani",
    category: "lunch",
    price: "70₹",
    description: "Fragrant rice layered with spiced vegetables and herbs.",
  },
  {
    id: 36,
    image: "images/dalchaawal.jpg",
    name: "Dal Chawal",
    category: "lunch",
    price: "50₹",
    description: "Classic combination of dal (lentils) and rice, served with pickle.",
  },
  {
    id: 37,
    image: "images/kachori.jpg",
    name: "Kachori",
    category: "lunch",
    price: "30₹",
    description: "Crispy fried pastry filled with spicy lentil mixture.",
  },
  {
    id: 38,
    image: "images/sarsonkasaag.jpg",
    name: "Sarson Da Saag",
    category: "lunch",
    price: "70₹",
    description: "Mustard greens cooked with spices, served with makki di roti.",
  },
  {
    id: 39,
    image: "images/vegthali.jpg",
    name: "Veg Thali",
    category: "lunch",
    price: "120₹",
    description: "A wholesome meal with a variety of vegetarian dishes, rice, and bread.",
  },
  {
    id: 40,
    image: "images/biryani.jpg",
    name: "Hyderabadi Biryani",
    category: "lunch",
    price: "200₹",
    description: "Spiced rice and meat dish, known for its rich flavors and aroma.",
  },

  // Evening Snacks
  {
    id: 41,
    image: "images/allupakoda.jpg",
    name: "Allu Pakoda",
    category: "evening",
    price: "20₹",
    description: "Crispy and spicy potato fritters, perfect for evening tea.",
  },
  {
    id: 42,
    image: "images/samosa.jpg",
    name: "Samosa",
    category: "evening",
    price: "10₹",
    description: "Golden fried pastry filled with spiced potatoes and peas, a classic snack.",
  },
  {
    id: 43,
    image: "images/burger.jpg",
    name: "Burger",
    category: "evening",
    price: "70₹",
    description: "Juicy patty with fresh vegetables and sauces, a satisfying evening meal.",
  },
  {
    id: 44,
    image: "images/pizza.jpg",
    name: "Pizza",
    category: "evening",
    price: "80₹",
    description: "Cheesy and delicious pizza with your choice of toppings.",
  },
  {
    id: 45,
    image: "images/pavbhaji.jpg",
    name: "Pav Bhaji",
    category: "evening",
    price: "50₹",
    description: "Spicy mashed vegetables served with buttered bread rolls.",
  },
  {
    id: 46,
    image: "images/dhokla.jpg",
    name: "Dhokla",
    category: "evening",
    price: "40₹",
    description: "Steamed savory cake made from fermented rice and chickpea batter.",
  },
  {
    id: 47,
    image: "images/bhelpuri.jpg",
    name: "Bhel Puri",
    category: "evening",
    price: "30₹",
    description: "A tangy and spicy puffed rice snack mixed with vegetables and tamarind sauce.",
  },
  {
    id: 48,
    image: "images/pakora.jpg",
    name: "Pakora",
    category: "evening",
    price: "25₹",
    description: "Mixed vegetable fritters, served with mint chutney.",
  },
  {
    id: 49,
    image: "images/cheesesticks.jpg",
    name: "Cheese Sticks",
    category: "evening",
    price: "35₹",
    description: "Crispy cheese sticks served with marinara sauce.",
  },
  {
    id: 50,
    image: "images/springrolls.jpg",
    name: "Spring Rolls",
    category: "evening",
    price: "50₹",
    description: "Crispy rolls filled with vegetables and served with sweet chili sauce.",
  },
  {
    id: 51,
    image: "images/chips.jpg",
    name: "Chips",
    category: "evening",
    price: "20₹",
    description: "Crispy potato chips, perfect for snacking.",
  },
  {
    id: 52,
    image: "images/cheeseballs.jpg",
    name: "Cheese Balls",
    category: "evening",
    price: "40₹",
    description: "Crispy and cheesy balls, served with dipping sauce.",
  },
  {
    id: 53,
    image: "images/fruitchaat.jpg",
    name: "Fruit Chaat",
    category: "evening",
    price: "45₹",
    description: "A tangy and spicy mix of fresh fruits.",
  },
  {
    id: 54,
    image: "images/masalapopcorn.jpg",
    name: "Masala Popcorn",
    category: "evening",
    price: "25₹",
    description: "Popcorn tossed with spicy masala.",
  },
  {
    id: 55,
    image: "images/chevda.jpg",
    name: "Chevda",
    category: "evening",
    price: "30₹",
    description: "Spicy and crunchy mixture of nuts, seeds, and fried lentils.",
  },
  {
    id: 56,
    image: "images/tikki.jpg",
    name: "Aloo Tikki",
    category: "evening",
    price: "20₹",
    description: "Crispy potato patties served with chutneys.",
  },
  {
    id: 57,
    image: "images/momos.jpg",
    name: "Momos",
    category: "evening",
    price: "50₹",
    description: "Steamed dumplings filled with vegetables or meat.",
  },
  {
    id: 58,
    image: "images/vegpakora.jpg",
    name: "Veg Pakora",
    category: "evening",
    price: "30₹",
    description: "Fried vegetable fritters served with chutney.",
  },
  {
    id: 59,
    image: "images/chanachat.jpg",
    name: "Chana Chaat",
    category: "evening",
    price: "40₹",
    description: "Spicy chickpea salad with onions, tomatoes, and chutneys.",
  },
  {
    id: 60,
    image: "images/keemafry.jpg",
    name: "Keema Fry",
    category: "evening",
    price: "60₹",
    description: "Spicy minced meat stir-fry with onions and spices.",
  },

  // Dinner Items
  {
    id: 61,
    image: "images/nonvegthali.jpg",
    name: "Non-Veg Thali",
    category: "dinner",
    price: "180₹",
    description: "A complete meal with a variety of non-vegetarian dishes, rice, and bread.",
  },
  {
    id: 62,
    image: "images/vegthali.jpg",
    name: "Veg Thali",
    category: "dinner",
    price: "120₹",
    description: "A wholesome meal with a variety of vegetarian dishes, rice, and bread.",
  },
  {
    id: 63,
    image: "images/chickenbiryani.jpg",
    name: "Chicken Biryani",
    category: "dinner",
    price: "200₹",
    description: "Aromatic basmati rice cooked with tender chicken pieces and spices.",
  },
  {
    id: 64,
    image: "images/fishcurry.jpg",
    name: "Fish Curry",
    category: "dinner",
    price: "220₹",
    description: "Fresh fish cooked in a tangy and spicy curry, served with rice.",
  },
  {
    id: 65,
    image: "images/dalmakhani.jpg",
    name: "Dal Makhani",
    category: "dinner",
    price: "150₹",
    description: "Creamy and rich lentil curry, a vegetarian favorite.",
  },
  {
    id: 66,
    image: "images/malaikofta.jpg",
    name: "Malai Kofta",
    category: "dinner",
    price: "170₹",
    description: "Soft paneer and vegetable dumplings in a rich and creamy tomato gravy.",
  },
  {
    id: 67,
    image: "images/lambcurry.jpg",
    name: "Lamb Curry",
    category: "dinner",
    price: "250₹",
    description: "Tender lamb pieces cooked in a rich and spicy gravy.",
  },
  {
    id: 68,
    image: "images/paneerbuttermasala.jpg",
    name: "Paneer Butter Masala",
    category: "dinner",
    price: "160₹",
    description: "Paneer cubes in a creamy tomato-based sauce.",
  },
  {
    id: 69,
    image: "images/vegetablekorma.jpg",
    name: "Vegetable Korma",
    category: "dinner",
    price: "140₹",
    description: "Mixed vegetables in a mildly spiced and creamy sauce.",
  },
  {
    id: 70,
    image: "images/chickpeacurry.jpg",
    name: "Chickpea Curry",
    category: "dinner",
    price: "130₹",
    description: "Hearty chickpeas cooked in a spiced gravy, served with rice or bread.",
  },
  {
    id: 71,
    image: "images/muttonkorma.jpg",
    name: "Mutton Korma",
    category: "dinner",
    price: "220₹",
    description: "Spicy and flavorful mutton curry with aromatic spices.",
  },
  {
    id: 72,
    image: "images/chaap.jpg",
    name: "Masala Chaap",
    category: "dinner",
    price: "230₹",
    description: "Prawns cooked in a spicy masala, best enjoyed with rice.",
  },
  {
    id: 73,
    image: "images/butterchicken.jpg",
    name: "Butter Chicken",
    category: "dinner",
    price: "200₹",
    description: "Rich and creamy chicken curry with a buttery texture.",
  },
  {
    id: 74,
    image: "images/vegbiryani.jpg",
    name: "Veg Biryani",
    category: "dinner",
    price: "150₹",
    description: "Flavorful rice dish with mixed vegetables and spices.",
  },
  {
    id: 75,
    image: "images/chickenkorma.jpg",
    name: "Chicken Korma",
    category: "dinner",
    price: "180₹",
    description: "Chicken cooked in a rich and creamy sauce with spices.",
  },
  {
    id: 76,
    image: "images/eggplantcurry.jpg",
    name: "Eggplant Curry",
    category: "dinner",
    price: "140₹",
    description: "Eggplant cooked in a spiced tomato gravy.",
  },
  {
    id: 77,
    image: "images/muttonroganjosh.jpg",
    name: "Mutton Rogan Josh",
    category: "dinner",
    price: "250₹",
    description: "Spicy and flavorful mutton curry with Kashmiri spices.",
  },
  {
    id: 78,
    image: "images/palakpaneer.jpg",
    name: "Palak Paneer",
    category: "dinner",
    price: "150₹",
    description: "Paneer cubes cooked in a rich spinach gravy.",
  },
  {
    id: 79,
    image: "images/khichdi.jpg",
    name: "Khichdi",
    category: "dinner",
    price: "80₹",
    description: "Comforting and easy-to-digest rice and lentil dish.",
  },
  {
    id: 80,
    image: "images/raita.jpg",
    name: "Raita",
    category: "dinner",
    price: "50₹",
    description: "Cooling yogurt dish with spices and vegetables, perfect with biryani.",
  },

  // Desserts
  {
    id: 81,
    image: "images/gulabjamun.jpg",
    name: "Gulab Jamun",
    category: "dessert",
    price: "30₹",
    description: "Sweet and syrup-soaked milk balls, a classic Indian dessert.",
  },
  {
    id: 82,
    image: "images/rasgulla.jpg",
    name: "Rasgulla",
    category: "dessert",
    price: "35₹",
    description: "Soft and spongy cheese balls soaked in sugar syrup.",
  },
  {
    id: 83,
    image: "images/kajukatli.jpg",
    name: "Kaju Katli",
    category: "dessert",
    price: "40₹",
    description: "Rich and creamy cashew nut fudge, cut into diamond shapes.",
  },
  {
    id: 84,
    image: "images/rasmalai.jpg",
    name: "Rasmalai",
    category: "dessert",
    price: "45₹",
    description: "Soft paneer dumplings soaked in sweetened milk and saffron.",
  },
  {
    id: 85,
    image: "images/jalebi.jpg",
    name: "Jalebi",
    category: "dessert",
    price: "25₹",
    description: "Crispy and syrup-soaked spiral-shaped sweet.",
  },
  {
    id: 86,
    image: "images/laddu.jpg",
    name: "Laddu",
    category: "dessert",
    price: "30₹",
    description: "Sweet and round dessert made from flour, sugar, and ghee.",
  },
  {
    id: 87,
    image: "images/barfi.jpg",
    name: "Barfi",
    category: "dessert",
    price: "50₹",
    description: "Sweet confection made from condensed milk, often garnished with nuts.",
  },
  {
    id: 88,
    image: "images/sohanpapdi.jpg",
    name: "Sohan Papdi",
    category: "dessert",
    price: "35₹",
    description: "Flaky and crispy sweet made from sugar, flour, and ghee.",
  },
  {
    id: 89,
    image: "images/khir.jpg",
    name: "Kheer",
    category: "dessert",
    price: "40₹",
    description: "Creamy rice pudding flavored with cardamom and garnished with nuts.",
  },
  {
    id: 90,
    image: "images/sandesh.jpg",
    name: "Sandesh",
    category: "dessert",
    price: "30₹",
    description: "Soft and delicate Bengali sweet made from fresh paneer.",
  },
  {
    id: 91,
    image: "images/icecream.jpg",
    name: "Ice Cream",
    category: "dessert",
    price: "50₹",
    description: "Cold and creamy ice cream available in various flavors.",
  },
  {
    id: 92,
    image: "images/mysorepak.jpg",
    name: "Mysore Pak",
    category: "dessert",
    price: "40₹",
    description: "Rich and dense sweet made from chickpea flour, ghee, and sugar.",
  },
  {
    id: 93,
    image: "images/fruitcake.jpg",
    name: "Fruit Cake",
    category: "dessert",
    price: "60₹",
    description: "Moist cake loaded with assorted dried fruits and nuts.",
  },
  {
    id: 94,
    image: "images/treaclepudding.jpg",
    name: "Treacle Pudding",
    category: "dessert",
    price: "55₹",
    description: "Sticky and sweet pudding served with custard.",
  },
  {
    id: 95,
    image: "images/cheesecake.jpg",
    name: "Cheesecake",
    category: "dessert",
    price: "65₹",
    description: "Rich and creamy cheesecake with a graham cracker crust.",
  },
  {
    id: 96,
    image: "images/cremebrulee.jpg",
    name: "Crème Brûlée",
    category: "dessert",
    price: "70₹",
    description: "Classic French dessert with a caramelized sugar crust.",
  },
  {
    id: 97,
    image: "images/fruitparfait.jpg",
    name: "Fruit Parfait",
    category: "dessert",
    price: "45₹",
    description: "Layered dessert with yogurt, fresh fruit, and granola.",
  },
  {
    id: 98,
    image: "images/pannaCotta.jpg",
    name: "Panna Cotta",
    category: "dessert",
    price: "60₹",
    description: "Creamy Italian dessert with a smooth texture, often served with berry sauce.",
  },
  {
    id: 99,
    image: "images/chocolatecake.jpg",
    name: "Chocolate Cake",
    category: "dessert",
    price: "55₹",
    description: "Decadent chocolate cake with layers of rich frosting.",
  },
  {
    id: 100,
    image: "images/applecrumble.jpg",
    name: "Apple Crumble",
    category: "dessert",
    price: "50₹",
    description: "Warm apple crumble topped with a buttery streusel, served with vanilla ice cream.",
  }
];

export default Menu;
